FROM golang:1.16-buster

WORKDIR /usr/src/app

COPY /material-applications/example-backend /usr/src/app

EXPOSE 8080

ENV REQUEST_ORIGIN=http://localhost:5000

RUN go build && \
		useradd -m appuser

USER appuser

ENTRYPOINT ["./server"]

