FROM golang:1.16.7-alpine3.14

WORKDIR /usr/src/app

COPY /material-applications/example-backend /usr/src/app

EXPOSE 8080

ENV REQUEST_ORIGIN=http://localhost:5000

RUN go build && \
		addgroup -S appgroup && \
		adduser -S appuser -G appgroup

USER appuser

ENTRYPOINT ["./server"]

