version: "3.8"

services:
  frontend:
    ports:
      - 5000:5000
    build:
      context: .
      dockerfile: Dockerfile.front
    environment:
      - REACT_APP_BACKEND_URL=http://localhost/api
  backend:
    ports:
      - 8080:8080
    build:
      context: .
      dockerfile: Dockerfile.back
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=database
      - POSTGRES_USER=anhtumai
      - POSTGRES_PASSWORD=password
  redis:
    image: redis
    ports:
      - 6379:6379
  database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=anhtumai
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  proxy:
    depends_on:
      - frontend
      - backend
      - redis
      - database
    restart: always
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
