version: "3.8"

services:
  frontend:
    ports:
      - 3000:3000
    build:
      context: ./blog-list-frontend-v2
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:3003
    depends_on:
      - backend
    networks:
      - mern-app
  backend:
    ports:
      - 3003:3003
    build:
      context: ./blog-list-backend
    environment:
      - MONGODB_URI=mongodb+srv://fullstack:fullstackopen2021@cluster0.awmni.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
      - SECRET=mysecret
    networks:
      - mern-app
networks:
  mern-app:
    driver: bridge
