version: "3.8"

services:
  frontend:
    ports:
      - 3000:3000
    build:
      context: ./blog-list-frontend-v2
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:3003
    depends_on:
      - backend
    networks:
      - mern-app
  backend:
    ports:
      - 3003:3003
    build:
      context: ./blog-list-backend
    environment:
      - MONGODB_URI=mongodb://mongo:27017/bloglist
      - SECRET=mysecret
    networks:
      - mern-app
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db

networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
