version: "3.8"

services:
  frontend:
    ports:
      - 5000:5000
    build:
      context: .
      dockerfile: Dockerfile.front
  backend:
    ports:
      - 8080:8080
    build:
      context: .
      dockerfile: Dockerfile.back
