version: "3.8"

services:
  frontend:
    ports:
      - 5000:5000
    build:
      context: .
      dockerfile: Dockerfile.front
  backend:
    ports:
      - 8080:8080
    build:
      context: .
      dockerfile: Dockerfile.back
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=database
      - POSTGRES_USER=anhtumai
      - POSTGRES_PASSWORD=password
  redis:
    image: redis
    ports:
      - 6379:6379
  database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=anhtumai
